name: Validate Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install --registry https://registry.npmjs.org
    - run: npm run build

      # - name: Install Dependencies
      #   run: npm ci
      #   env:
      #     NPM_RAZORPAY_TOKEN: ${{ secrets.NPM_TOKEN }}
      #     GITHUB_ACCESS_TOKEN: ${{ secrets.TOKEN }}

      # - name: ESLint PR Check
      #   run: |
      #     eslint \
      #     --output-file eslint_report.json \
      #     --no-error-on-unmatched-pattern \
      #     --format json \
      #     ${{ steps.changed-files.outputs.all_modified_files }}
      #   continue-on-error: true

      # - name: Annotate ES lint issues
      #   uses: ataylorme/eslint-annotate-action@v2
      #   id: eslint-annotator
      #   with:
      #     report-json: "eslint_report.json"
      #     check-name: "Eslint Report"
