name: Validate Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    continue-on-error: false
    name: Validate
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v9.3
        with:
          files: |
            .(js|json|jsx|ts|tsx)$

      - name: Node version
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - name: Install Dependencies
        run: npm ci
        env:
          TOKEN: ${{ github.GITHUB_TOKEN }}

      - name: ESLint PR Check
        run: |
          eslint \
          --output-file eslint_report.json \
          --no-error-on-unmatched-pattern \
          --format json \
          ${{ steps.changed-files.outputs.all_modified_files }}
        continue-on-error: true

      - name: Annotate ES lint issues
        uses: ataylorme/eslint-annotate-action@v2
        id: eslint-annotator
        with:
          report-json: "eslint_report.json"
          check-name: "Eslint Report"
