name: Validate Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    continue-on-error: false
    name: Validate
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v9.3
        with:
          files: |
            .(js|json|jsx|ts|tsx)$

      - name: Node version
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - name: Install Dependencies
        run: npm ci

      - name: ESLint PR Check
        run: |
          npx eslint \
          --output-file eslint_report.json \
          --no-error-on-unmatched-pattern \
          --format json \
          ${{ steps.changed-files.outputs.all_modified_files }}
        continue-on-error: true

      # - name: Filter ESLint Errors
      #   run: |
      #     const fs = require('fs');

      #     // Read the ESLint report
      #     const eslintReport = JSON.parse(fs.readFileSync('eslint_report.json', 'utf8'));

      #     // Filter errors with 'ruleId' containing "custom-rules/"
      #     const filteredReport = eslintReport.map(file => {
      #       file.messages = file.messages.filter(message => message.ruleId.includes('custom-rules/'));
      #       return file;
      #     });

      #     // Save the filtered report
      #     fs.writeFileSync('filtered_eslint_report.json', JSON.stringify(filteredReport, null, 2));

      - name: List Files
        run: ls -la

      - name: Filter ESLint Errors
        run: |
          # Use jq to filter ESLint errors by 'ruleId'
          jq '[.[] | {filePath: .filePath, messages: [.messages[] | select(.ruleId | contains("custom-rules/"))]}]' eslint_report.json > filtered_eslint_report.json

      - name: Annotate ES lint issues
        uses: ataylorme/eslint-annotate-action@v2
        id: eslint-annotator
        with:
          report-json: "eslint_report.json"
          check-name: "Eslint Report"
