name: I18n Linter
on:
  pull_request:
    types:
      [
        labeled
      ]
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Verify Linter running
    outputs:
      has_ignore_label: ${{ steps.linter-check.outputs.label_found }}
    steps:
      - name: Check for linter ignore label
        id: check-linter-label
        run: |
          echo "GitHub event JSON: ${{ toJson(github.event.pull_request) }}"
          github_labels=$(jq --raw-output '.[] .name' <<< '${{ toJson(github.event.pull_request.labels) }}')

          if [ -n "$github_labels" ] && [ "$github_labels" != "ignore-i18n-linter" ]; then
            echo "Linter ignore label found, exiting further process gracefully"
            echo "label_found=true" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "No linter ignore label found, linter will proceed now."
            echo "label_found=false" >> $GITHUB_OUTPUT
          fi

  linter:
    runs-on: ubuntu-latest
    name: I18n Linter
    needs: verify
    if: needs.linter.outputs.has_ignore_label == 'false'
    outputs:
      has_error: ${{ steps.linter-check.outputs.hardcoding_found }}
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v9.3
        with:
          files: |
            .(js|jsx|ts|tsx|json)$

      - name: Node version
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - name: Install Dependencies
        run: npm ci

      - name: Custom Rules Check
        run: |
          npx eslint \
          --output-file errors_report.json \
          --no-error-on-unmatched-pattern \
          --format json \
          ${{ steps.changed-files.outputs.all_modified_files }}
        continue-on-error: true

      - name: Filter I18n Errors
        run: |
          # Use jq to filter i18n errors by 'ruleId'
          jq '[.[] | {filePath: .filePath, messages: [.messages[] | select(.ruleId | contains("custom-rules/"))], errorCount: (.messages | map(select(.ruleId | contains("custom-rules/"))) | length)}]' errors_report.json > eslint_report.json

      - name: Check ESLint Report for i18n Errors
        id: linter-check
        run: |

          # Specify the path to your JSON file
          json_file="eslint_report.json"

          # Check if the JSON file exists
          if [ ! -f "$json_file" ]; then
            echo "JSON file '$json_file' does not exist."
            exit 0
          fi

          report_contents=$(cat eslint_report.json)
          # Check if report_contents is non-empty
          if [ -n "$report_contents" ]; then
            error_found=false

            for obj in $(echo "${report_contents}" | jq -r '.[] | @base64'); do
              _jq() {
              echo ${obj} | base64 --decode | jq -r ${1}
              }
              errorCount=$(echo $(_jq '.errorCount'))
              if [ "$errorCount" -gt 0 ]; then
                error_found=true
              fi
            done

            # Check if error was found and take further action if needed
            if [ "$error_found" = true ]; then
              echo "I18n errors detected."
              echo "hardcoding_found=true" >> $GITHUB_OUTPUT
            fi
          else
            echo "No i18n errors found empty. No processing performed."
            echo "hardcoding_found=false" >> $GITHUB_OUTPUT
            exit 0
          fi
        shell: bash

      - name: Annotate ES lint issues
        uses: ataylorme/eslint-annotate-action@v2
        id: eslint-annotator
        with:
          report-json: "eslint_report.json"
          check-name: "Eslint Report"

  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    needs: linter
    if: failure() && needs.linter.outputs.has_error == 'true'
    steps:
      - name: Send a slack alert to I18N team
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":error: *Urgent Alert!* :error:"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":exclamation: *Pull Request:* ${{ github.event.pull_request.title }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":bust_in_silhouette: *Author:* *<${{ github.event.pull_request.user.html_url }}|${{ github.event.pull_request.user.login }}>*"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":construction: *Status:* Open"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":fire: *Message:*\n Some errors has been found, requesting a review from @internationalization-fe"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":link: *PR URL:* <${{ github.event.pull_request.html_url || github.event.head_commit.url }}>"
                  }
                }
              ]
            }
        env:
          # SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK